configfile:
  - profiles/clades/builds.yaml # Specific builds for this profile

# Always print the commands that will be run to the screen for debugging.
printshellcmds: True
keep-going: True

# Print log files of failed jobs
show-failed-logs: True

cores: 12
